version: '3'
services:
  mongodb:
    image: mongo:4
    ports:
    - "27017:27017"
    volumes:  
    - './data:/data/db'
  nodejs:
    build: ./server/
    ports:
     - "3001:3001"
    volumes:
      - ./server/:/home/app
      - /home/app/node_modules
    links:
      - mongodb
    depends_on:
      - mongodb
  reactjs:
    build: ./client/
    ports:
     - "3000:3000"
    volumes:
      - ./client/:/home/app
      - /home/app/node_modules