version: '3'
services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
    - "27017:27017"
    volumes:  
    - './data:/data/db'
  nodejs:
    container_name: nodejs
    build: ./server/
    ports:
     - "3001:3001"
    volumes:
      - ./server/:/home/app
      - /home/app/node_modules
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      WAIT_HOSTS: mongodb:27017
  reactjs:
    container_name: reactjs
    build: ./client/
    ports:
     - "3000:3000"
    volumes:
      - ./client/:/home/app
      - /home/app/node_modules